$('#addHouse').click(function(){
	$.ajax({
		url:'index.php',
		type:'GET',
		data:{
			action:'addHouse',
		},
		success:function(responce){
			$('.content').html(responce);
			console.log(responce);
		}
	})
})
